# Timestamp value in nanosecond or the unit defined by the system.
builtin_interfaces/Time stamp

# Desired vehicle speed in m/s
float32 velocity

# Desired acceleration / deceleration rate in m/s2
float32 long_accel

# Desired front wheel turning radius
float32 front_wheel_angle

# Desired rear wheel turning radius
float32 rear_wheel_angle

# Desired front wheel rotation rate
float32 front_wheel_angle_rotation_rate

# Desired front wheel rotation rate
float32 rear_wheel_angle_rotation_rate

# Desired front wheel torque
float32 front_wheel_torque

# Desired rear wheel torque
float32 rear_wheel_torque
